/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-23 00:59:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import tripMate.model.BlogMainDTO;

public final class blogpart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1745368944776L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Documents/javafullstack2025/06_MVC프로젝트/발표자료/TripMate/TripMate/ws/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TripMate/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("tripMate.model.BlogMainDTO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>이미지 슬라이더</title>\n");
      out.write("\n");
      out.write("<!-- Swiper CSS & JS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css\"/>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js\"></script>\n");
      out.write("<link href=\"css/header.css\" rel=\"stylesheet\">\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("\n");
      out.write("  .crrbtn {\n");
      out.write("    display: block;\n");
      out.write("    margin: 20px auto;\n");
      out.write("    border: none;\n");
      out.write("    color: white;\n");
      out.write("    background-color: #66d162;\n");
      out.write("    width: 100px;\n");
      out.write("    height: 35px;\n");
      out.write("    border-radius: 40px;\n");
      out.write("    font-weight: bold;\n");
      out.write("    cursor: pointer;\n");
      out.write("    transition: background-color 0.3s ease;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .crrbtn:hover {\n");
      out.write("    background-color: #4caf50;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .swiper {\n");
      out.write("    width: 1300px;\n");
      out.write("    height: 310px;\n");
      out.write("    margin: 0 auto;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .swiper-slide {\n");
      out.write("    text-align: center;\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: center;\n");
      out.write("    align-items: center;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .swiper-slide img {\n");
      out.write("    border-radius: 20px;\n");
      out.write("    width: 230px;\n");
      out.write("    height: 300px;\n");
      out.write("    object-fit: cover;\n");
      out.write("    box-shadow: 0 4px 12px rgba(0,0,0,0.15);\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .swiper-button-next,\n");
      out.write("  .swiper-button-prev {\n");
      out.write("    color: #999;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .swiper-pagination-bullet-active {\n");
      out.write("    background-color: rgb(203, 120, 120);\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .title {\n");
      out.write("    margin-top: 40px;\n");
      out.write("    text-align: center;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .title h2 {\n");
      out.write("    font-size: 28px;\n");
      out.write("    color: #2c3e50;\n");
      out.write("    margin-bottom: 5px;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .title p {\n");
      out.write("    color: #888;\n");
      out.write("    font-size: 14px;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .content {\n");
      out.write("    margin-top: 40px;\n");
      out.write("    text-align: center;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .content input {\n");
      out.write("    font-size: 16px;\n");
      out.write("    width: 1300px;\n");
      out.write("    height: 100px;\n");
      out.write("    border-radius: 10px;\n");
      out.write("    padding: 10px;\n");
      out.write("    border: 1px solid #ccc;\n");
      out.write("    background-color: #fff;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .home-link {\n");
      out.write("    display: block;\n");
      out.write("    text-align: center;\n");
      out.write("    margin-top: 20px;\n");
      out.write("    text-decoration: none;\n");
      out.write("    font-weight: bold;\n");
      out.write("    color: #3498db;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .home-link:hover {\n");
      out.write("    text-decoration: underline;\n");
      out.write("  }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  window.addEventListener(\"load\", function () {\n");
      out.write("    new Swiper(\".promotion .swiper\", {\n");
      out.write("      slidesPerView: 5,\n");
      out.write("      spaceBetween: 10,\n");
      out.write("      centeredSlides: true,\n");
      out.write("      loop: true,\n");
      out.write("      autoplay: {\n");
      out.write("        delay: 3000\n");
      out.write("      },\n");
      out.write("      speed: 1000,\n");
      out.write("      navigation: {\n");
      out.write("        nextEl: \".promotion .swiper-button-next\",\n");
      out.write("        prevEl: \".promotion .swiper-button-prev\",\n");
      out.write("      }\n");
      out.write("    });\n");
      out.write("  });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header>\n");
      out.write("	<div class=\"logo\">\n");
      out.write("		<a href=\"");
      out.print(request.getContextPath());
      out.write("/main\"><img class=\"logoImg\" src=\"image/logo.png\"\n");
      out.write("			alt=\"\"></a>\n");
      out.write("	</div>\n");
      out.write("	<div>\n");
      out.write("		<a href=\"");
      out.print(request.getContextPath());
      out.write("/myTrip\">여행일정</a>\n");
      out.write("	</div>\n");
      out.write("	<div>\n");
      out.write("		<a href=\"");
      out.print(request.getContextPath());
      out.write("/mainsearch\">관광지</a>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	<div>\n");
      out.write("		<a href=\"");
      out.print(request.getContextPath());
      out.write("/mainblog\">블로그</a>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	<div>\n");
      out.write("		<a href=\"");
      out.print(request.getContextPath());
      out.write("/myPage\">마이페이지</a>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("</header>\n");
      out.write("\n");

    BlogMainDTO blog = (BlogMainDTO) request.getAttribute("blog");
    int imgIndex = (int) request.getAttribute("imgIndex");

      out.write("\n");
      out.write("\n");
      out.write("<form action=\"");
      out.print(request.getContextPath());
      out.write("/update\" method=\"get\">\n");
      out.write("  <input type=\"hidden\" name=\"id\" value=\"");
      out.print( blog.getId() );
      out.write("\">\n");
      out.write("  <button type=\"submit\" class=\"crrbtn\">수정</button>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<div class = \"title\">\n");
      out.write("<h2 style=\"text-align: center;\">");
      out.print( blog.getTitle() );
      out.write("</h2>\n");
      out.write("<p style=\"text-align: center;\">");
      out.print( blog.getRegDate() );
      out.write("</p>\n");
      out.write("</div>\n");
      out.write("<div class=\"promotion\">\n");
      out.write("  <div class=\"swiper\">\n");
      out.write("    <div class=\"swiper-wrapper\">\n");
      out.write("      ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <div class=\"swiper-button-prev\"></div>\n");
      out.write("    <div class=\"swiper-button-next\"></div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"content\">\n");
      out.write("  <input type=\"text\" style=\"width: 1300px; height: 100px;\" \n");
      out.write("         value=\"");
      out.print( blog.getContent() );
      out.write("\" readonly>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/blogpart.jsp(173,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("img");
    // /WEB-INF/views/blogpart.jsp(173,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/blogpart.jsp(173,6) '${blog.imageList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${blog.imageList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("        <div class=\"swiper-slide\">\n");
          out.write("          <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/upload/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"슬라이드 이미지\">\n");
          out.write("        </div>\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }
}
