/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-23 01:00:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import tripMate.model.PersonalCost;

public final class personalCost_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("tripMate.model.PersonalCost");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>TripMate - 개인 정산 내역</title>\r\n");
      out.write("<!-- 헤더 스타일 -->\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/header.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- Font Awesome 아이콘 폰트 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("<link href=\"css/personalCost.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

	// 바디 안쪽에서만 꺼내기
	String sd_code = (String) request.getAttribute("sd_code"); // 여행 코드
	String tripName = (String) request.getAttribute("tripName"); // 여행 제목
	String tripPeriod = (String) request.getAttribute("tripPeriod"); // 여행 기간
	String selectedIndex = request.getParameter("personIndex"); // 선택된 사람 인덱스
	String[] nameList = (String[]) request.getAttribute("nameList"); // 사람 닉네임 배열
	PersonalCost[][] pendingGiveList = (PersonalCost[][]) request.getAttribute("pendingGiveList"); // 대기 내역 배열
	PersonalCost[][] completedGiveList = (PersonalCost[][]) request.getAttribute("completedGiveList"); // 완료 내역 배열
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"logo\">\r\n");
      out.write("			<a href=\"");
      out.print(request.getContextPath());
      out.write("/main?sd_code=");
      out.print(sd_code);
      out.write("\">\r\n");
      out.write("				<img class=\"logoImg\"\r\n");
      out.write("				src=\"");
      out.print(request.getContextPath());
      out.write("/image/logo.png\" alt=\"로고\">\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<a href=\"");
      out.print(request.getContextPath());
      out.write("/myTrip?sd_code=");
      out.print(sd_code);
      out.write("\">여행일정</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<a href=\"\">관광지</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<a href=\"\">블로그</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<a href=\"");
      out.print(request.getContextPath());
      out.write("/myPage?sd_code=");
      out.print(sd_code);
      out.write("\">마이페이지</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<!-- 상단 타이틀 및 네비게이션 -->\r\n");
      out.write("	<div class=\"top\">\r\n");
      out.write("		<h1>\r\n");
      out.write("			<i class=\"fa-solid fa-calculator\"></i> 여행비 가계부\r\n");
      out.write("		</h1>\r\n");
      out.write("		<div class=\"button\">\r\n");
      out.write("			<button class=\"button1\"\r\n");
      out.write("				onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/cost?sd_code=");
      out.print(sd_code);
      out.write("'\">지출\r\n");
      out.write("				내역</button>\r\n");
      out.write("			<button class=\"button2\"\r\n");
      out.write("				onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/personalCost?sd_code=");
      out.print(sd_code);
      out.write("'\">개인\r\n");
      out.write("				정산 내역</button>\r\n");
      out.write("			<button class=\"button3\"\r\n");
      out.write("				onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/totalCost?sd_code=");
      out.print(sd_code);
      out.write("'\">총\r\n");
      out.write("				지출 내역</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 본문 -->\r\n");
      out.write("	<div class=\"bottom\">\r\n");
      out.write("		<div class=\"content_wrap\">\r\n");
      out.write("			<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("				<!-- 제목 및 사람 선택 -->\r\n");
      out.write("				<div class=\"content_title\">\r\n");
      out.write("					<h2>\r\n");
      out.write("						");
      out.print(tripPeriod);
      out.write("\r\n");
      out.write("						<span>여행 정산 내역</span><br>\r\n");
      out.write("						");
      out.print(tripName);
      out.write("\r\n");
      out.write("					</h2>\r\n");
      out.write("					<select id=\"personSelect\" class=\"person_select\">\r\n");
      out.write("						<option value=\"\" disabled hidden>정산 내역을 볼 사람 선택</option>\r\n");
      out.write("						");

						for (int i = 0; i < nameList.length; i++) {
							String sel = String.valueOf(i).equals(selectedIndex) ? "selected" : "";
						
      out.write("\r\n");
      out.write("						<option value=\"");
      out.print(i);
      out.write('"');
      out.write(' ');
      out.print(sel);
      out.write('>');
      out.print(nameList[i]);
      out.write(" 님\r\n");
      out.write("						</option>\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- 정산 내역 표시 -->\r\n");
      out.write("				<div class=\"day_container\">\r\n");
      out.write("					");

					for (int i = 0; i < nameList.length; i++) {
					
      out.write("\r\n");
      out.write("					<div class=\"day\" data-person=\"");
      out.print(i);
      out.write("\">\r\n");
      out.write("						<!-- 대기중 내역 -->\r\n");
      out.write("						<div class=\"personal_wrap\">\r\n");
      out.write("							<div class=\"section-header1\">정산 대기중</div>\r\n");
      out.write("							");

							PersonalCost[] pendings = pendingGiveList[i];
							int visiblePendingCount = 0;
							for (PersonalCost pc : pendings) {
								if (!pc.getUserCode().equals(pc.getPayer())) {
									visiblePendingCount++;
								}
							}
							if (visiblePendingCount == 0) {
							
      out.write("\r\n");
      out.write("							<div class=\"empty-text\">내역이 없습니다.</div>\r\n");
      out.write("							");

							} else {
							for (PersonalCost pc : pendings) {
								if (pc.getUserCode().equals(pc.getPayerCode()))
								    continue;
							
      out.write("\r\n");
      out.write("							<div class=\"give-item\">\r\n");
      out.write("								<div class=\"info\">\r\n");
      out.write("									<i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("									<div class=\"p\">\r\n");
      out.write("										<strong>");
      out.print(pc.getPayer());
      out.write("</strong>님께\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"amount\">\r\n");
      out.write("									");
      out.print(String.format("%,d원", pc.getPersonCost()));
      out.write("\r\n");
      out.write("									<form action=\"");
      out.print(request.getContextPath());
      out.write("/personalCost\"\r\n");
      out.write("										method=\"post\" style=\"display: inline-block; margin-left: 8px;\">\r\n");
      out.write("										<input type=\"hidden\" name=\"personalCostId\"\r\n");
      out.write("											value=\"");
      out.print(pc.getPersonalCostId());
      out.write("\" /> <input type=\"hidden\"\r\n");
      out.write("											name=\"personIndex\" value=\"");
      out.print(i);
      out.write("\" /> <input type=\"hidden\"\r\n");
      out.write("											name=\"sd_code\" value=\"");
      out.print(sd_code);
      out.write("\">\r\n");
      out.write("										<button type=\"submit\" class=\"complete-btn\">정산완료</button>\r\n");
      out.write("									</form>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							");

							}
							}
							
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 완료된 내역 -->\r\n");
      out.write("						<div class=\"personal_wrap\">\r\n");
      out.write("							<div class=\"section-header2\">완료된 내역</div>\r\n");
      out.write("							");

							PersonalCost[] completes = completedGiveList[i];
							int visibleCompleteCount = 0;
							for (PersonalCost pc : completes) {
								if (!pc.getUserCode().equals(pc.getPayerCode())) {
									visibleCompleteCount++;
								}
							}
							if (visibleCompleteCount == 0) {
							
      out.write("\r\n");
      out.write("							<div class=\"empty-text\">내역이 없습니다.</div>\r\n");
      out.write("							");

							} else {
							for (PersonalCost pc : completes) {
								if (pc.getUserCode().equals(pc.getPayerCode()))
								    continue;
							
      out.write("\r\n");
      out.write("							<div class=\"give-item completed\">\r\n");
      out.write("								<div class=\"info\">\r\n");
      out.write("									<i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("									<div class=\"p\">\r\n");
      out.write("										<strong>");
      out.print(pc.getPayer());
      out.write("</strong>님께\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"amount\">");
      out.print(String.format("%,d원", pc.getPersonCost()));
      out.write("</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							");

							}
							}
							
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("    const select = document.getElementById('personSelect');\r\n");
      out.write("    const days   = document.querySelectorAll('.day');\r\n");
      out.write("    // 페이지 로드 시 기본 선택\r\n");
      out.write("    window.addEventListener('DOMContentLoaded', () => {\r\n");
      out.write("        if (!select.value && select.options.length > 1) {\r\n");
      out.write("            select.selectedIndex = 1;\r\n");
      out.write("        }\r\n");
      out.write("        select.dispatchEvent(new Event('change'));\r\n");
      out.write("    });\r\n");
      out.write("    // 선택된 사람 인덱스에 따라 해당 div 표시\r\n");
      out.write("    select.addEventListener('change', () => {\r\n");
      out.write("        days.forEach(d => {\r\n");
      out.write("            d.style.display = (d.dataset.person === select.value) ? 'flex' : 'none';\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
